### ISSUE TITLE
dodaj Žar brez utvar med projekte

### ISSUE THREAD

**Issue by cylebrity** [danesjenovdan/danesjenovdan.si#27]
Kratek tekst: 
Re-akcija ob vnovičnem prikazu cesarjeve golote ali zakaj je Pahor slab predsednik. Namesto, da bi prižgali televizijski PR žar, smo mu na internetu raje podkurili z vsebinsko kritiko. Stanje pečenosti: gotof!

Metrika:
Na družbenih omrežjih deljeno: 1805-krat

Dolg tekst:
14. februarja leta 2016 ni zaznamovala le vsakokratna komercializacija ljubezni, pač pa tudi predsednika države. Na ta dan je namreč komercialna televizija predvajala oddajo Na žaru z Borutom Pahorjem v glavni vlogi. Zbadljiv format oddaje je zaradi gosta povsem zvodenel in se spremenil v učinkovit začetek nove volilne kampanje. Na DJND smo ob tem pozornost s simpatičnih pobalinstev preusmerili na konkretne Pahorjeve politične napake. Predsednik je resna funkcija, zato terja tudi resno kritiko: vzeli smo ga s TV-žara in ga dali v internetno pečico, iz katere je prišel bistveno bolj osmoljen kot iz oddaje.

**Comment by maschinna** [comment]
ob priliki rabim še angleško verzijo

**Comment by muki** [comment]
http://danesjenovdan.si/projekti/
