### ISSUE TITLE
apdejt tekstov za nove projekte na danesjenovdan.si/projekti

### ISSUE THREAD

**Issue by cylebrity** [danesjenovdan/danesjenovdan.si#30]
Alternacija

V tvitih politikov in strank smo besede begunec, migrant itn. zamenjali z besedo žid in z vizualno zasnovo spletne kampanje namignili na nekaj vsem znanih spornih simbolov, da bi bilo jasno: od odkrite fašistične propagande jih loči le še beseda!

na Facebooku deljeno 1620-krat

Alternacija

Da bi pokazali na problematičnost diskurza o beguncih, smo marca 2016 pripravili spletno kampanjo, v kateri smo tvite politikov in političnih strank spremenili tako, da smo besede begunec, migrant itn. zamenjali z besedo žid. Šele, ko besede, namenjene beguncem, preusmerimo na skupino, do katere je Zahod patološko empatičen, postane jasno, da se naša družba odkrito spogleduje s fašizmom. Politična propaganda zoper begunce spominja na nacistično, kar ustvarja družbo strahu, v kateri namesto o ekonomski razpravljamo o migrantski krizi, poleg pasov pa zategujemo še vojaške škornje. Sieg!

oglej si spletno kampanjo - zapri

Prostovid

Kritični študentski komentarji stanja slovenskega prostora v obliki nasprotujočih si vizij prihodnosti, postavljeni na spletni ogled iz udobnega naslanjača. Sporočilo je jasno: vsi smo soodgovorni za bodoč videz okolice!

št. predstavljenih krajev 9

Prostovid 

S Prostovidom smo konec aprila 2016 študentom in njihovim mentorjem z Biotehniške fakultete in Fakultete za arhitekturo UL pomagali predstaviti rezultate delavnice o možnih prihodnostih slovenskega prostora. Študentje so predelali vizualne materiale storitve Google street view na način, da kažejo bodisi pesimistično bodisi optimistično prostorsko vizijo, mi pa smo jih uredili in predstavili na za splet primeren način. Vsakdo je postavljen pred enostavno odločitev: si želim krajine, kot jo bo neizogibno oblikovalo nadaljevanje trenutnih trendov "urejanja" prostora, ali pa bom zahteval/-a prijaznejši, vključujoč in naravi prijazen pristop.

oglej si spletno mesto projekta - zapri

**Comment by muki** [comment]
manjka ti še fotka za te projekte, this is on hold

**Comment by LepkoQQ** [comment]
closed by 2e9139a0e75afa45beab55d66a06ca19d252fed9
